import * as fs from "fs";
import * as path from "path";

function main() {
  const currentDir = __dirname;
  const workspaceRoot = path.resolve(currentDir, "..", "..");
  let envPath = path.join(workspaceRoot, ".env");
  const outputPath = path.join(
    workspaceRoot,
    "synapse-plugin",
    ".agents",
    "config.toml",
  );

  if (!fs.existsSync(envPath)) {
    const fallbackPath = path.join(workspaceRoot, "synapse-portal", ".env");
    if (fs.existsSync(fallbackPath)) {
      envPath = fallbackPath;
    } else {
      console.error(
        `Error: .env file not found at ${envPath} or ${fallbackPath}`,
      );
      process.exit(1);
    }
  }

  // Parse .env
  const envContent = fs.readFileSync(envPath, "utf-8");
  const envVars: { [key: string]: string } = {};

  for (let line of envContent.split("\n")) {
    line = line.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    if (line.includes("=")) {
      const index = line.indexOf("=");
      const key = line.substring(0, index).trim();
      let val = line.substring(index + 1).trim();
      // Strip quotes
      if (
        (val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.substring(1, val.length - 1);
      }
      envVars[key] = val;
    }
  }

  const userName = envVars["SYNAPSE_USER_NAME"] || "Developer";
  const commLang = envVars["SYNAPSE_COMMUNICATION_LANGUAGE"] || "Vietnamese";
  const docLang = envVars["SYNAPSE_DOCUMENT_OUTPUT_LANGUAGE"] || "Vietnamese";
  const codingLevel = envVars["SYNAPSE_CODING_LEVEL"] || "3";

  const tomlContent = `# Auto-generated by render_config.ts - DO NOT EDIT MANUALLY
[agent]
user_name = "${userName}"
communication_language = "${commLang}"
document_output_language = "${docLang}"
coding_level = "${codingLevel}"
`;

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, tomlContent, "utf-8");
  console.log(`Successfully rendered configuration to ${outputPath}`);
}

main();
